"""Generate an isolated 5x run gitlab-ci.yml. untrusted inputs are shell-quoted"""


from __future__ import annotations

import re
import shlex

from app.services.validation.branch import is_safe_node_name, is_safe_repo_path

JOB_PREFIX = "verify_"
# A Docker image ref: registry/namespace/name:tag — no whitespace/newlines, so it
# cannot break out of the YAML scalar it is interpolated into (YAML-injection guard).
_IMAGE_RE = re.compile(r"^[A-Za-z0-9_][A-Za-z0-9_./:@-]{0,199}$")




def generate_ci_yaml(*, file_path: str, test_name: str, runs: int, image: str) -> str:
    """A self contained ci config: runs sequential, isolated pytest invocations"""

    if not is_safe_repo_path(file_path):
        raise ValueError(f"unsafe file_path: {file_path!r}")
    if not is_safe_node_name(test_name):
        raise ValueError(f"unsafe test_name: {test_name!r}")
    if not _IMAGE_RE.match(image):
        raise ValueError(f"unsafe ci image: {image!r}")



    # Verify the SPECIFIC failing test by its pytest node id (file::test). This is
    # the blueprint's intent ("run only the affected test"): it isolates the fix and
    # avoids re-running other tests in the file that the Fixer may not have touched.
    # NOTE: test_name must be the REAL pytest function name (not a dashboard label) —
    # a node id that matches nothing yields pytest "no tests ran" (exit 1).
    target = shlex.quote(f"{file_path}::{test_name}")


    lines: list[str] = [
        "# Generated by Minari Validator - isolated flaky-test verification.",
        "stages:",
        "  - verify",
        "",
        "default:",
        f"  image: {image}",
        "  cache: {}                       # no caching, full isolation",
        "  interruptible: true",
        "  timeout: 5 minutes",
        "  before_script:",
        "    - python -m pip install -q --disable-pip-version-check pytest",
        "    - if [ -f requirements.txt ]; then pip install -q -r requirements.txt; fi",
        "",
    ]
    for i in range(1, runs + 1):
        job = f"{JOB_PREFIX}{i}"
        lines += [
            f"{job}:",
            "  stage: verify",
            "  allow_failure: true            # collect every run; gate evaluates per-job",
            "  script:",
            f"    - pytest {target} -p no:cacheprovider -q",
        ]
        if i > 1:                       
            lines += [f"  needs: [\"{JOB_PREFIX}{i - 1}\"]"]
        lines.append("")
    return "\n".join(lines)